### ISSUE TITLE
Search by exact match

### ISSUE THREAD

**Issue by jkrug** [ongr-io/FilterManagerBundle#138]
As a user i want to type in a ean and get exactly that product if found.

**Comment by murnieza** [comment]
This is already implemented, but actually "exact" or "not exact" search is achieved not by configuring filters, but by adjusting `Elasticsearch` mapping. This is totally not FilterManagerBundle specific but pure `Elasticsearch` mapping configuration question.

User should be aware of `Elasticsearch` principles to achieve this. There is big entry in [official documentation](https://www.elastic.co/guide/en/elasticsearch/guide/current/_finding_exact_values.html#_finding_exact_values) which explains how to achieve "exact" match for fields with different data types. Do we want to repeat everything in our documentation?

**Comment by jkrug** [comment]
Well look, i don't want always the exact match. Sometimes the user inserts "blue t-shirt" in the search box; then i want to show them all blue t-shirts. But if he enters the exact product number / ean of a single product, i want to show only this one or - even better - redirect him on the details page.

**Comment by saimaz** [comment]
@jkrug this is exactly what @murnieza meant. `FilterManager` is a component which can provide filter combinations in an easy and maintanable way. How you specify the documents, how do you want to analyze them it's totaly up to the user. 

This component never will have an artificial intelegence to decide out of nothing what user wants. 

I'm closing this issue because it's not relevant or is not in the right place.
