### ISSUE TITLE
Investigate if there is possible to create filter list cache

### ISSUE THREAD

**Issue by saimaz** [ongr-io/FilterManagerBundle#30]
Filter manager builds filter list from configuration. In this process there are so many recursions and blocks rebuilding operations, just to make sure build correctly relations on selected filters. 

What if we could cache all these builds and set only values to already builded list.

**Comment by martiis** [comment]
Yes it would be possible by using something like [stash-bundle](https://github.com/tedious/TedivmStashBundle)

**Comment by saimaz** [comment]
I would prefer doctrine cache instead.

**Comment by saimaz** [comment]
So in a nutshel would be great to preapre a stateless filter tree's and only set the values. So whanever we generate selected filters tree, we can calculate a check sum out of it and cache, then figure out how to set only a values instead of exponential recursion.

**Comment by saimaz** [comment]
@trandangtri, can you write here research results? Is there any possible solution to improve performace for this particular case?

**Comment by ndinh215** [comment]
Hi @saimaz , I took care this issue. My suggested solution:
![cache_diagram](https://cloud.githubusercontent.com/assets/8800820/11657390/f8d9f1ea-9dee-11e5-87ad-51f719e1d2c3.png)
The light blue region is running in reality. And we just implement the pink region for caching configuration.

With this implementation, when we changes some info in config file, the system will get the cached filter tree to build the configuration instance before normalizing & merging with updated config file.

@mvar suggested that we should not implement anything here, because when we deploy new one, the  system will auto build cache config and we will not touch this again.

Please give us your information. Thanks.

**Comment by saimaz** [comment]
I think you got the problem in a wrong way. There are no problems with the config cache etc. I just mentioned config in short description before that from this configuration the fiter tree will be build. The thing is when FilterManager wants to set selected values from the request or just get the whole filters it runs recursively through all filters, and when there are any relations it iterates everything again. My thought was, is there possible to avoid these recursive iterations by caching the first time result and make that tree stateless for later to set only values and that's it.
